"""
Main entry point for the application.
"""

from modules.example_module import example_function

def main():
    print("If you've made it this far, know that this is all bullshit.")
    print("This is a fake project generated by chatgpt.")
    print("Why ?")
    print("Some HR niggers say they wanna see the contributions chart glow green")
    print("Others say they wanna see some 'smart AI' shit on my github profile (I'm a javascript developer applying for web dev positions -_-)")
    print("¯\_(ツ)_/¯")
    print('Commit 1')
    print('Commit 2')
    print('Commit 3')
    print('Commit 4')
    print('Commit 5')
    print('Commit 6')
   
    example_function()

if __name__ == "__main__":
    main()
